[package]
name = "pos_local"
version = "1.0.6"
description = "Punto de venta local con Tauri"
authors = ["pruebas-tauri"]
license = "MIT"
edition = "2021"

[lib]
name = "pos_local_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
escpos = "0.19.0"

[target.'cfg(windows)'.dependencies]
printers = "2.3.0"
